module com {
    module dotsandboxes {
        module corbaservice {
            module service {
                typedef sequence<octet> ByteArray;
                interface Service {
                    ByteArray processRequest(in ByteArray request);
                    oneway void sendRequest(in ByteArray request);
                };
            };
        };
    };
};
